version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: make build
      - run: make dialyzer_plt
      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build

  test:
    requires:
      - build
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: make test

  cs:
    requires:
      - build
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: make cs

  cover:
    requires:
      - build
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: make cover
      - store_artifacts:
          path: cover/excoveralls.html
          destination: cover/excoveralls.html

  dialyzer:
    requires:
      - build
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: make dialyzer

workflows:
  version: 2
  build-test-cs-cover:
    jobs:
      - build
      - test:
          requires:
            - build
      - cs:
          requires:
            - build
      - cover:
          requires:
            - build
      - dialyzer:
          requires:
            - build